package com.inova.mobile.bdilshopify.typhography

enum class BDiLTypoStyle {
    REGULAR_WHITE_12,
    REGULAR_WHITE_16,
    REGULAR_GRAY_16,
    REGULAR_BLACK_16,
    REGULAR_BLACK_14,
    REGULAR_GRAY_14,
    REGULAR_BLACK_12,
    REGULAR_PRIMARY_12,
    MEDIUM_BLACK_16,
    MEDIUM_PRIMARY_14,
    MEDIUM_WHITE_16,
    MEDIUM_BLACK_24,
    MEDIUM_PRIMARY_16,
    MEDIUM_PRIMARY_24,
    MEDIUM_PRIMARY_30
}